# Generated by Django 4.2 on 2023-04-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='formulae',
        ),
        migrations.AddField(
            model_name='subject',
            name='formulae',
            field=models.ManyToManyField(to='memoir.formula'),
        ),
    ]
